Artists
WildCodeSchool/lille-0920b-js-voltali-voltasic pull request #14
Opened 2020-11-13 17:15 UTC by Sarahshr

added artist carousel

2020-11-13 17:47 UTC, LoicBrassart commented
Please assign me when the SM did her/his review

2020-11-13 18:18 UTC, ThomasMlh submitted a review, later dismissed
It's ok ! 👍

2020-11-14 09:18 UTC, Fx-Colliot submitted a review, later dismissed
yes

2020-11-15 07:48 UTC, LoicBrassart requested changes
Saw no Evil
@Fx-Colliot and @ThomasMlh , you didn't read this code: there are red blocks indicating bad code, it's utterly unmissable if you scroll this page. :anger: 
Next time I see something like this, I'll let the PR pass

2020-11-15 07:48 UTC, LoicBrassart commented on src/components/homepage/Artists.jsx
> +    return mock.items;
This return does nothing (you don't use the return value in your useEffect code)

2020-11-15 07:48 UTC, LoicBrassart commented on src/components/homepage/Home.jsx
> +<<<<<<< HEAD
ACHTUNG !
There are conflict artefacts in this file !
Nobody read this code before me -_-

2020-11-15 09:39 UTC, Fx-Colliot submitted a review, later dismissed
ok je n'ai pas vu d'erreur

2020-11-15 11:09 UTC, ThomasMlh approved these changes
SnE !

2020-11-15 13:10 UTC, LoicBrassart approved these changes
No more Evil

2020-11-15 13:30 UTC, merged