Caroussel
WildCodeSchool/lille-0920b-js-voltali-voltasic pull request #7
Opened 2020-11-11 20:00 UTC by Sarahshr

Add Trend musics' carousel

2020-11-11 20:06 UTC, Fx-Colliot approved these changes, later dismissed
perfect

2020-11-11 20:07 UTC, ThomasMlh commented
It's ok for me ! 👍

2020-11-11 20:08 UTC, ThomasMlh approved these changes, later dismissed
It's ok for me ! 👍

2020-11-12 00:20 UTC, ThomasMlh approved these changes, later dismissed
Good 👍

2020-11-12 06:20 UTC, Fx-Colliot approved these changes, later dismissed
ok

2020-11-12 08:56 UTC, Fx-Colliot approved these changes, later dismissed
good for me

2020-11-12 17:03 UTC, LoicBrassart requested changes

2020-11-12 17:03 UTC, LoicBrassart commented on src/App.js
> +//import TrendingMusic from "./components/TrendingMusic";
Dead code !

2020-11-12 17:08 UTC, LoicBrassart approved these changes
NmE !

2020-11-12 17:11 UTC, ThomasMlh approved these changes
It's ok !

2020-11-12 17:12 UTC, merged